### ISSUE TITLE
Multiple Instances?

### ISSUE THREAD

**Issue by timbroder** [geerlingguy/ansible-role-redis#26]
I have a need to run 2 redis instances on the same server. 

Each would be the same, but using a different backup strategy. (Underlying requirement is a queue with sensitive data that can't get written to disk, and accepting the failure tolerance that goes with that)

Would it be possible to provision both instances using this role? Or would I be better off installing 1 (which I already have) and using Ansible file manipulation to create the second one "by hand"?

Thanks

**Comment by timbroder** [comment]
This actually ended up being a lot easier than I thought it would. Putting notes here for posterity:

Read: http://chrislaskey.com/blog/342/running-multiple-redis-instances-on-the-same-server/

In the post_tasks of the playbook where you install the original instance, re-use the original `redis.conf.j2` and set any variables that you want to change. 

Important ones are:

* port
* logfile
* config file
* pidfile

```
post_tasks:
    - name: Redis Plutonium data directory
      file: path={{ redis_plutonium_dbdir }} state=directory mode=0751 owner=redis group=redis
    - name: Ensure Redis Plutonium is configured.
      template:
        src: templates/redis.conf.j2
        dest: "{{ redis_plutonium_conf_path }}"
        mode: 644
      vars:
        redis_daemon: "{{ redis_plutonium_daemon }}"
        redis_port: "{{ redis_plutonium_port }}"
        redis_logfile: "{{ redis_plutonium_logfile }}"
        redis_dbdir: "{{ redis_plutonium_dbdir }}"
        redis_save: "{{ redis_plutonium_save }}"
        redis_appendonly: "{{ redis_plutonium_appendonly }}"
        redis_appendfsync: "{{ redis_plutonium_appendfsync }}"
        redis_instance: "-p"
      notify: restart redis
    - name: Ensure Redis Plutonium has startup script
      template:
        src: templates/redis-server-p.sh.j2
        dest: /etc/init.d/redis-server-p
        mode: 751
    - name: Ensure Redis Plutonium is running and enabled on boot.
      service: "name={{ redis_plutonium_daemon }} state=started enabled=yes"
    - name: adjust perms of newrelic file
```
