### ISSUE TITLE
redis_requirepass not working

### ISSUE THREAD

**Issue by fega** [geerlingguy/ansible-role-redis#44]
Hello, I just use the role, but I'm getting an error running a Node.Js instance:

```
Redis server does not require a password, but a password was supplied.
```

which means that redis is not working:

```
vars:
    nodejs_version: "10.x"
    nodejs_npm_global_packages:
      - name: pm2
    redis_requirepass: "aaa..."
  roles:
    - geerlingguy.nodejs
    - geerlingguy.redis
```
