### ISSUE TITLE
redis 6.2.1 Failed with result 'protocol'

### ISSUE THREAD

**Issue by svitru** [geerlingguy/ansible-role-redis#59]
redis 6.2.1 Failed with result 'protocol'
Fixed after adding "supervised auto" to templates/redis.conf.j2

OS VERSION="20.04.2 LTS (Focal Fossa)"

  pre_tasks:
    - name: Add chris-lea APT repositories
      apt_repository:
        repo: "ppa:redislabs/redis"
        state: present
        update_cache: yes

**Comment by nicovs** [comment]
as from: https://github.com/redis/redis/blob/unstable/redis.conf#L249-L265 (vs the v5 config: https://github.com/redis/redis/blob/5.0/redis.conf#L138-L147)

There is a need to uncomment (or add an include file via the var: redis_includes, check the [Readme](https://github.com/geerlingguy/ansible-role-redis/blob/master/README.md)
with content  `supervised auto`

**Comment by StanBright** [comment]
Can we reopen this? I was just bitten by this :/

**Comment by smutel** [comment]
Same issue, any workaround ?

**Comment by smutel** [comment]
As a workaround:
```
daemonize no
supervised auto
```

**Comment by nicovs** [comment]
I do it like this:
Setup a host or group var on your redis_servers group
```yaml
redis_include: |
  supervised auto
```
Add this to your playbook:
```yaml
- name: create redis folder
  file:
    path: /etc/redis
    state: directory

- set_fact:
    redis_includes: [ '/etc/redis/redis_include.conf' ]
  when: redis_include is defined

- name: Redis Include extra options
  template: 
    src: "{{ playbook_dir }}/templates/redis/redis_include.conf.j2"
    dest: /etc/redis/redis_include.conf
    owner: redis
    group: redis
    mode: 0640
  notify: 
    - restart redis
  when: redis_include is defined

- import_role:
    name: geerlingguy.redis
```

and a template in: templates/redis/redis_include.conf.j2

```
{{ ansible_managed | comment }}

{{ redis_include }}
```
